language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - vue-source

install:
  - npm ci
  - npm run generate --fail-on-page-error

script:
  - mkdir -p dist/_nuxt/static/img
  - cp assets/img/security_onion_solutions_rings.png dist/_nuxt/static/img/security_onion_solutions_rings.png
  - echo "Skipping tests"

deploy:
  provider: pages
  skip_cleanup: true
  fqdn: securityonionsolutions.com
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  target_branch: master
  on:
    branch: vue-source
