language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - vue-source

install:
  - npm install
  - npm run generate --fail-on-page-error

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  fqdn: securityonionsolutions.com
  github_token: $GITHUB_TOKEN
  keep_history: true
  local-dir: dist
  target_branch: master
  on:
    branch: vue-source
