- title: Onsite
  iconType: el-icon-edit-outline
  content: |
    <p>
      We are the <strong>only</strong> official source for onsite Security Onion training and our instructors
      are the only Security Onion Certified Instructors in the world!
    </p>
    <p>
      We offer multi-day comprehensive training classes with lots of labs and real-world case studies for reinforcement!
      Students receive printed course materials and walk out of class with a Certificate of Completion ready to make their adversaries cry!
    </p>
    <p>
      <a href="https://securityonionsolutions.com/onsitetraining">Click here</a>
      for pricing and registration for Security Onion live public courses
    </p>
    <p>
      We are proud to offer GSA pricing through our partner IntelliGenesis!
      <br/>
      Eligible organizations, please <a href="mailto:onsitetrainingGSA@securityonionsolutions.com">email us here</a> for more information.
    </p>
  contactBlurb: Have at least 8 students and want private training at your facility in the continental United States?
  contactEmail: onsitetraining@securityonionsolutions.com
- title: Online
  iconType: el-icon-monitor
  content: |
    <p>
      We also offer online training via on-demand training modules. They are a cost-effective alternative to onsite training,
      but do not include the in-depth, hands-on labs that our onsite classes do.
    </p>
    <p>The following on-demand training modules are pre-recorded and can be accessed immediately upon payment and for 60 days thereafter:</p>
    <ul>
      <li>Security Onion 101: Introduction to Security Onion</li>
      <li>Security Onion 201: Best Practices for Production Deployments</li>
      <li>Security Onion 301: Best Practices for Distributed Deployments</li>
    </ul>
    <p><strong>Best value!</strong> Purchase all 3 classes in a discounted bundle!</p>
    <p><a href="https://onlinetraining.securityonionsolutions.com/">Click here</a> for pricing and registration for Security Onion on-demand training</p>
  contactBlurb: Have questions about online training?
  contactEmail: onlinetraining@securityonionsolutions.com
